#!/usr/bin/env python

from __future__ import print_function
from __future__ import division
from __future__ import absolute_import
from __future__ import unicode_literals

import os
import sys
import signal

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

from blueman.gui.dialogs.Adapters import BluemanAdapters
from blueman.Functions import set_proc_title

#support running uninstalled
_dirname = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if os.path.exists(os.path.join(_dirname, "CHANGELOG.md")):
    sys.path.insert(0, _dirname)

# Workaround introspection bug, gnome bug 622084
signal.signal(signal.SIGINT, signal.SIG_DFL)

if __name__ == '__main__':
    set_proc_title()
    adapter_name = None
    if len(sys.argv) > 1:
        adapter_name = sys.argv[1]
    blueman_adapters = BluemanAdapters(adapter_name)
    Gtk.main()

